CC = g++
CFLAGS = -std=c++2a -w

all: SSSP SSSP_Sarthak ComparerSSSP

SSSP: SSSP.cpp
	$(CC) $(CFLAGS) -o SSSP SSSP.cpp

SSSP_Sarthak: SSSP_Sarthak.cpp
	$(CC) $(CFLAGS) -o SSSP_Sarthak SSSP_Sarthak.cpp

ComparerSSSP: ComparerSSSP.cpp
	$(CC) $(CFLAGS) -o ComparerSSSP ComparerSSSP.cpp

clean:
	rm -f SSSP SSSP_Sarthak ComparerSSSP
